name: CI

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - develop
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/**'

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3 

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello one-line script !

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 1er echo du multi-line script,
          echo 2eme echo du multi-line script,
          echo 3eme echo multi-line script.
